### ISSUE TITLE
Datapacks Crashing With Latest Rift

### ISSUE THREAD

**Issue by sweetsosweet** [DimensionalDevelopment/Rift#14]
I'm getting a crash with some of my datapacks that I didn't have with the previous version of Rift. When I load them without Rift the game works fine. I've also found that some datapacks aren't working anymore with Rift whereas they work fine in vanilla.

[Crash Report](https://pastebin.com/fxHCqL6H)

Rift version is 1.0.2-33

**Mods Loaded:**
EnderCompass-Rift-1.13-1.0.2.jar
HalfLogs-1.1.0.jar
MouseTweaksForRift-0.1.2-mc1.13.jar
stockpile-0.1.0.jar

**Comment by DatrixTHLK** [comment]
I'm getting the same issue also.
