### ISSUE TITLE
realm menu looks broken - Rift-1.0.3-44

### ISSUE THREAD

**Issue by MSandro** [DimensionalDevelopment/Rift#17]
I've now installed the newest rift wersion to the official minecraft launcher. My operationg system is Manjaro Linux (based on Arch Linux) but I think this shouldnt matter.

![bildschirmfoto von 2018-08-13 18-36-17](https://user-images.githubusercontent.com/10937159/44045166-036f636e-9f28-11e8-9ef5-50260df38c93.png)

![bildschirmfoto von 2018-08-13 18-38-23](https://user-images.githubusercontent.com/10937159/44045186-11049cf6-9f28-11e8-80e4-2c5c830389b0.png)

I've didn't find any other texture glitches in the game.

**Comment by UpcraftLP** [comment]
can confirm, had the same issue
