### ISSUE TITLE
[Bug/Crash] Rift crashes when generating new worlds

### ISSUE THREAD

**Issue by UpcraftLP** [DimensionalDevelopment/Rift#18]
When generating a new World, Rift crashes with a NullPointerException.
[Crash Log](https://github.com/DimensionalDevelopment/Rift/files/2284504/crash-2018-08-13_21.46.46-server.txt)

Thie Issue is caused by `File#listFiles()` returning `null` here.
https://github.com/DimensionalDevelopment/Rift/blob/4b64e4efde69890850298154f15c12ae30a1e5f6/src/main/java/org/dimdev/rift/resources/ModPack.java#L98

seems like the issue was introduced in https://github.com/DimensionalDevelopment/Rift/commit/263d0b0bf479c6d4e9d5c8f4b8aef0da91d04104

**Comment by MSandro** [comment]
In rift Rift-1.0.3-44 new worlds generating fine on my client. Or do you mean on server side?

**Comment by UpcraftLP** [comment]
> I'd rename this, since the crash log is that of a server.
rename? why? it's rift that is crashing, not a server.
