### ISSUE TITLE
Files in the mods folder are listed as resource packs

### ISSUE THREAD

**Issue by Knito58** [DimensionalDevelopment/Rift#19]
As the mods folder is a rift-only folder i cannot blame vanilla MC for that. Sorry.

**Comment by Runemoro** [comment]
Mods *are* resource packs. They can have everything a resource or data pack has, and they can also have code on top.

**Comment by Knito58** [comment]
I'm used to Forge and there the mod files are not shown in the resourcepacks folder. There you only see what normal MC users think resourcepacks are: Graphic and sound files and all the files which really are in the resourcepacks folder. And the mod.jar files are not in that folder, whether they are resource files or not: They have their own "mods" folder. But they are shown as if they were situated in the resourcepacks folder. 

I can live with that. No problem. But I strongly believe that I will not stay the only one to report this.

You to decide. It is the best modding option for 1.13 atm. Nobody will drop Rift for that as long as Forge is not out yet.

**Comment by Runemoro** [comment]
Mods are resource packs in Forge too, but it seems like Forge hides them from the list for some reason (at least in 1.12, it may change in 1.13).

Listing them in the resource pack and data pack lists also has the practical advantage of letting the player sort them in case two mods override the same vanilla (or other mod's) resource.

Most importantly, I'd like for Rift mods should be considered an extension of vanilla resource and data packs. They could contain only resources, but can also contain code on top. This fits with the idea that the Rift API is designed mainly to extend vanilla with new content such as blocks, items, biomes, entities, dimensions, commands, etc.

**Comment by Knito58** [comment]
Of course you're right. It fits well into the "keep-it-simple" concept of RIFT. I can see the advantages. 
It's not a bug - it's a feature. Thanks for responding and thanks for the good work.
