### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null(server side)

### ISSUE THREAD

**Issue by SDUBZ** [DimensionalDevelopment/Rift#22]
Rift:1.13-1.0.3-45
minecraft:1.13
[latest.txt](https://github.com/DimensionalDevelopment/Rift/files/2293603/latest.txt)

if you need anymore info let me know
:)

**Comment by sjx233** [comment]
Outdated mods?

**Comment by Runemoro** [comment]
This is caused by AEI and MouseTweaks. You should remove them from your mods on the server since they're client-only mods.

**Comment by asiekierka** [comment]
You should consider adding "client"/"server"/"listenersClient"/"listenersServer" fields.
