### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by nift4** [DimensionalDevelopment/Rift#46]
Hey!
1.13.1 is #RestrictedToVanilla
1.13.1 hasn't thousand changes also I hope 1.13.1 support comes out before 1.14 ;)

**Comment by Mgazul** [comment]
wait for mcp1.13.1

**Comment by MissPotato** [comment]
How can I check on the status for MCP? The only thing I've found is the Old MCPatcher for beta Minecraft that was basically just Optifine.

**Comment by ZombieHDGaming** [comment]
1.13.1 is not restricted to Vanilla and will be arriving within the next few weeks. I'm locking this as there is no need for talk on this.
