### ISSUE TITLE
TileEntityRenderer not rendering

### ISSUE THREAD

**Issue by raphydaphy** [DimensionalDevelopment/Rift#5]
I've noticed that my tileentityrenderer isnt doing anything after successfully registering it using the TileEntityRendererAdder interface. Using the code below to register and declare the renderer, it only prints out 'render render render' one or two times when my block is first placed and never again even when block updates occur or the tileentity is updated. I dont mention the renderer class anywhere else in the code though, so i may be missing some important function calls and im sorry if thats the case.

```
// in main class which implements TileEntityRendererAdder
@Override
public void addTileEntityRenderers(Map<Class<? extends TileEntity>, TileEntityRenderer<? extends TileEntity>> renderers)
{
    System.out.println("added renderer");
    renderers.put(TileEntityAltar.class, new AltarRenderer());
}

// the renderer class
public class AltarRenderer extends TileEntityRenderer<TileEntityAltar>
{
    public void func_199341_a(TileEntityAltar altar, double x, double y, double z, float partialTicks, int destroyStage) // i think this is the render method???
    {
        System.out.println("render render render");
    }
}
```

**Comment by jredfox** [comment]
use notch names as func_ is a forge srg name. I don't think he has mcp installed

**Comment by jredfox** [comment]
was the name in forge or rift tile entity render? it's the the mcp-srg. notch names are the obfuscated names that are totally unreadable

**Comment by raphydaphy** [comment]
i made a mod with just a tileentityrenderer and it worked so i guess this is on my side

**Comment by raphydaphy** [comment]
I have found the source of this problem - adding this line https://gist.github.com/raphydaphy/cae7e915972a85f12abd3e12048ff20c#file-tesrdebug-java-L89 will cause the tileEntityRenderer to never render again after it has recieved a data packet from the server. That gist is a self contained mod which demonstrates the problem

**Comment by raphydaphy** [comment]
turns out you can avoid this issue by not reading the position when reading from NBT if the read is for rendering purposes only, guess this isnt too important then

**Comment by jredfox** [comment]
TileEntity.readFromNBT() will set xyz pos to 0,0,0 it's not a rift issue it's your logic issue.
