### ISSUE TITLE
Rift connection issue?

### ISSUE THREAD

**Issue by Bismar7** [DimensionalDevelopment/Rift#52]
Downloaded and installed the most recent version here, loaded up minecraft with nothing in the mods folder. 

upon trying to connect I got this:
![cant connect](https://user-images.githubusercontent.com/44013825/46712728-489ebc80-cc07-11e8-9d9e-7f2767ebffae.PNG)

Tried downloading previous versions and installing them, no effect. 

When I run the non-rift version of 1.13.1 it works flawlessly.

I'm not even sure what the issue with this is, but I would like to be able to load my mods. Thanks for any help provided.

**Comment by ZombieHDGaming** [comment]
That's because Rift isn't 1.13.1.........Rift is only 1.13 for the moment. Closing the issue as it is not an actual issue.
