### ISSUE TITLE
Can Rift provide Guide for Installation?

### ISSUE THREAD

**Issue by xfl03** [DimensionalDevelopment/Rift#6]
I like this ModLoader, but when I tells some people to use it, I find it is hard to teach others installing it.
Could Rift provide an installer or guide to help users to install it?

**Comment by Runemoro** [comment]
The installer will be improved in the next version. It will directly create a "Rift" option in the dropdown on the main screen, rather than just add a profile in Launch Options.

**Comment by xfl03** [comment]
Looking forward to it!
