### ISSUE TITLE
Rift does not work with some datapacks

### ISSUE THREAD

**Issue by Chris-sd154** [DimensionalDevelopment/Rift#66]
I am having a problem with Rift not being compatible with certain datapacks like the magic-sorting-system datapack. Minecraft will load but as soon as I try to open a world my game crashes...!?!?!?!???

**Comment by ZombieHDGaming** [comment]
Known issue, already fixed in dev.

**Comment by Chris-sd154** [comment]
What is "dev"?

**Comment by ZombieHDGaming** [comment]
Development.........most devs abbreviate it because everyone refers to it as dev and no real reason to say the full term. Its basic mod lingo
