### ISSUE TITLE
Rift for MC 1.13.2?

### ISSUE THREAD

**Issue by MSandro** [DimensionalDevelopment/Rift#70]
Hi I've found a Rift port for MC 1.13.2: https://jitpack.io/com/github/chocohead/rift/2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff/rift-2c400465c7e0b5abf4e643372fbd9a7e6d39e3ff.jar

Does anyone know from who it is and why there is no port for 1.13.2 on this repo?

**Comment by ZombieHDGaming** [comment]
Yes, he's a member of Dimensional Development and he's handling the 1.13.2 port. Chocohead just hasn't moved his work to our repos yet.

**Comment by ScaroMX** [comment]
that version gives me this error: 

The game crashed whilst unexpected error
Error: java.lang.VerifyError: Instruction type does not match stack map

Java is up to date.

**Comment by ZombieHDGaming** [comment]
@ScaroMX What Java version are you running? 8, 9, etc.

**Comment by ScaroMX** [comment]
> 
> 
> @ScaroMX What Java version are you running? 8, 9, etc.

Its 8  - 191

**Comment by Rei-57645** [comment]
Guys why is there another fork of this ?
Why not simply use one repo ?
Accept chocos PullRqeuest ?
