### ISSUE TITLE
Optifine and Rift

### ISSUE THREAD

**Issue by Paenthy** [DimensionalDevelopment/Rift#76]
Since last night, Optifine and Rift Voxelmap won't work together anymore due to CustomColors error path

i've submitted the issue already on Optifine page: https://github.com/sp614x/optifine/issues/2183 but could also be due to Rift.

**Comment by jakey1995abc** [comment]
This is very strange, I am getting this exact error as well since last night. So I guess something related to rift/optifine is connecting to a server which has now changed in some way or something?

**Comment by Chocohead** [comment]
Fixed in Chocohead/Rift@173f0df63a89f63e111401a5ab35fbf9c3582deb
