### ISSUE TITLE
Failed to download file. rift-1.0.4-SNAPSHOT.jar

### ISSUE THREAD

**Issue by Steffbeard** [DimensionalDevelopment/Rift#86]
Failed to download file. rift-1.0.4-SNAPSHOT.jar
Name: rift-1.0.4-SNAPSHOT.jar
URL: https://www.dimdev.org/maven/org/dimdev/rift/1.0.4-SNAPSHOT/rift-1.0.4-SNAPSHOT.jar
Error details: HTTP 404: Not Found
Filename on disk: d0a2-91ee-1747-fa08
Path: /var/folders/yp/98tdrwl11ps3_6j92cg_yw240000gn/T/d0a2-91ee-1747-fa08
Exists: file
![Screen Shot 2019-05-28 at 6 20 27 PM](https://user-images.githubusercontent.com/13314771/58516237-4e84e600-8175-11e9-8a7d-59a4f3a9c279.png)
![Screen Shot 2019-05-28 at 6 21 09 PM](https://user-images.githubusercontent.com/13314771/58516273-63617980-8175-11e9-92ca-2d0a2107410b.png)

**Comment by Runemoro** [comment]
You're using an unofficial build (ends in -SNAPSHOT) so there is no file on the dimdev maven.

**Comment by vacla** [comment]
rift 1.13.2 download from Chocohead ends always with -SNAPSHOT: https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar
This issue has been mentioned several times lately on the Discord from dimdev also

**Comment by vacla** [comment]
also this should be the first entry normally
`
            "name": "com.github.Chocohead:Rift:jitpack-SNAPSHOT",
            "url": "https://www.jitpack.io/"
`

not that with org.dimdev:rift:1.0.4-SNAPSHOT tho
